### ISSUE TITLE
Marks and Nodes are instantiated as new Classes instead of Services

### ISSUE THREAD

**Issue by cjprinse** [ueberdosis/prosemirror-to-html#35]
Because of Marks and Nodes are instantiated as new Classes, instead of services, it is impossible to inject other services in the Mark of Node. 
I think it would be better to have any kind of NodeRenderer/MarkRender, so you would be able to decorate or overwrite these renders.

**Comment by hanspagel** [comment]
Thanks! Could you provide code examples? I’m not too familiar with the mentioned patterns.

**Comment by hanspagel** [comment]
See my comment here: https://github.com/ueberdosis/prosemirror-to-html/pull/36#issuecomment-707031774
