### ISSUE TITLE
Bolding or italicizing a subselection of link text creates an HTML mess

### ISSUE THREAD

**Issue by jackmcdade** [ueberdosis/prosemirror-to-html#50]
**Describe the bug**
Bolding or italicizing a subselection of link text creates an HTML mess

**Steps to Reproduce**
1. Select some text
2. Make it a link
3. Select a substring of the link text and make it bold
4. The resulting HTML will have nested links inside links.

**Expected behavior**
Subselection should just have a single child node of the appropriate type and not another link node.

**Screenshots**

**Environment**
 - OS: All
 - Browser All
 - Version: Latest (1.29.4)
 - Mobile / Desktop: All

**Additional context**
As reported in https://github.com/statamic/cms/issues/3108

**Comment by hanspagel** [comment]
Added a failing test in #51. I’m afraid that’s not too easy to fix, but I’ll give it a try soon. Help would be highly appreciated.

**Comment by hanspagel** [comment]
Should be fixed in the latest release. Thanks for reporting!

**Comment by jackmcdade** [comment]
Woo!
