### ISSUE TITLE
Incompatibility with Tiptap?

### ISSUE THREAD

**Issue by j-schumann** [ueberdosis/prosemirror-to-html#65]
Hello,

we use TipTap in our frontend and convert the yDoc to JSON with the hocuspocs/TiptapTransformer which is later converted to HTML using the package.

The problem is that Tiptap uses camelCased node name (e.g. https://github.com/ueberdosis/tiptap/blob/main/packages/extension-horizontal-rule/src/horizontal-rule.ts#L24) while this package uses snake_case: https://github.com/ueberdosis/prosemirror-to-html/blob/main/src/Nodes/HorizontalRule.php#L7
Thus formatting is lost on conversion.

What is the reason for this difference, how is this best handled? Do we need to implement new Node classes in PHP with the adjusted names?

Thanks in advance!

```
// Output from the TiptapTransformer, uses the names from Tiptap
{ type: 'doc', content: [ { type: 'bulletList', content: [Array] } ] }

// what PHP receives:
{"type":"bulletList","content":[{"type":"listItem", ...
```

**Comment by hanspagel** [comment]
Done in https://github.com/ueberdosis/tiptap-php ✌️
