### ISSUE TITLE
Camel vs snake-case in node-types

### ISSUE THREAD

**Issue by rseyferth** [ueberdosis/prosemirror-to-html#67]
https://github.com/ueberdosis/prosemirror-to-html/blob/73f1d613bc15371c61751394e2b381dd498d69bb/src/Nodes/HardBreak.php#L7

The JSON output I get from tiptap uses `hardBreak` as the node-type, not `hard_break`. Is this a version issue?

**Comment by hanspagel** [comment]
Done in https://github.com/ueberdosis/tiptap-php
